import type { Task } from "@/types/schedule";

// Mock data based on the demo script: Sarah's schedule
const today = new Date().toISOString().split("T")[0];

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "CS 161 Lecture",
    description: "Operating Systems lecture, Gates B01",
    priority: "P1",
    start_time: `${today}T09:00:00`,
    end_time: `${today}T10:20:00`,
    energy_cost: 3,
    estimated_duration: 80,
    status: "scheduled",
    delegatable: false,
  },
  {
    id: "task-2",
    title: "Study Group — CS 229",
    description: "Machine learning pset review with group",
    priority: "P1",
    start_time: `${today}T10:30:00`,
    end_time: `${today}T12:00:00`,
    energy_cost: 4,
    estimated_duration: 90,
    status: "scheduled",
    delegatable: false,
  },
  {
    id: "task-3",
    title: "Gym — Cardio",
    description: "AOERC, 30 min run + stretching",
    priority: "P3",
    start_time: `${today}T12:00:00`,
    end_time: `${today}T13:00:00`,
    energy_cost: 2,
    estimated_duration: 60,
    status: "scheduled",
    delegatable: false,
  },
  {
    id: "task-4",
    title: "CS 229 Problem Set",
    description: "Pset 4 — due tomorrow 11:59pm",
    priority: "P0",
    start_time: `${today}T14:00:00`,
    end_time: `${today}T16:00:00`,
    energy_cost: 5,
    estimated_duration: 120,
    status: "scheduled",
    delegatable: false,
  },
  {
    id: "task-5",
    title: "Office Hours — Prof. Ng",
    description: "Ask about gradient descent question",
    priority: "P2",
    start_time: `${today}T16:00:00`,
    end_time: `${today}T17:00:00`,
    energy_cost: 3,
    estimated_duration: 60,
    status: "scheduled",
    delegatable: false,
  },
  {
    id: "task-6",
    title: "Reply to Prof. Martinez email",
    description: "RE: Research assistant position follow-up",
    priority: "P2",
    start_time: `${today}T17:00:00`,
    end_time: `${today}T17:15:00`,
    energy_cost: 1,
    estimated_duration: 15,
    status: "scheduled",
    delegatable: true,
    task_type: "email_reply",
  },
  {
    id: "task-7",
    title: "Slack — Update study group",
    description: "Let group know about schedule change for tomorrow",
    priority: "P3",
    start_time: `${today}T17:15:00`,
    end_time: `${today}T17:25:00`,
    energy_cost: 1,
    estimated_duration: 10,
    status: "scheduled",
    delegatable: true,
    task_type: "slack_message",
  },
];
